/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../include/throttle.h"
#include "../include/utils.h"
#include "../libopeninv/include/params.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_CheckAndLimit(void);
extern void test_CheckAndLimitHigh(void);
extern void test_CheckDualThrottle(void);
extern void test_CalcThrottle(void);
extern void test_RampThrottle(void);
extern void test_utils_change(void);
extern void test_utils_GetUserThrottleCommand(void);
extern void test_utils_ProcessThrottle(void);
extern void test_IgnoredTest(void);
extern void test_AnotherIgnoredTest(void);
extern void test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_throttle.cpp");
  run_test(test_CheckAndLimit, "test_CheckAndLimit", 24);
  run_test(test_CheckAndLimitHigh, "test_CheckAndLimitHigh", 42);
  run_test(test_CheckDualThrottle, "test_CheckDualThrottle", 50);
  run_test(test_CalcThrottle, "test_CalcThrottle", 64);
  run_test(test_RampThrottle, "test_RampThrottle", 75);
  run_test(test_utils_change, "test_utils_change", 79);
  run_test(test_utils_GetUserThrottleCommand, "test_utils_GetUserThrottleCommand", 85);
  run_test(test_utils_ProcessThrottle, "test_utils_ProcessThrottle", 90);
  run_test(test_IgnoredTest, "test_IgnoredTest", 117);
  run_test(test_AnotherIgnoredTest, "test_AnotherIgnoredTest", 122);
  run_test(test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented, "test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented", 127);

  return UnityEnd();
}
